### ISSUE TITLE
IllegalArgumentException can be thrown by WorkflowTest#getHeapUsage() when heap is full

### ISSUE THREAD

**Issue by sroughley** [3D-e-Chem/knime-testflow#14]
An `IllegalArgumentException` can be thrown, e.g.:

```
java.lang.IllegalArgumentException: committed = 536870912 should be < max = 536870910
	at java.management/java.lang.management.MemoryUsage.<init>(MemoryUsage.java:166)
	at nl.esciencecenter.e3dchem.knime.testing.core.ng.WorkflowTest.getHeapUsage(WorkflowTest.java:137)
	at nl.esciencecenter.e3dchem.knime.testing.core.ng.WorkflowMemLeakTest.<init>(WorkflowMemLeakTest.java:71)
```

when the heap is full at the start of or during test execution

This is a result of the constructor call in the `return` statement in the code below. 

The difference of `2` in the exception message between `committed` and `max` values is significant.  In particular, `MemoryUsage#getMax()` will return `-1` if there is no max value set, which appears to be the case for both `G1 Eden Space` and `G1 Survivor Space` memory pools.  The counting loop here therefore reduces the max value returned from the `G1 Old Gen` memory pool by `2`.

https://github.com/3D-e-Chem/knime-testflow/blob/1fa09ace6c82f3d84d21c6e3fe5cb479ceb770a2/plugin/src/java/nl/esciencecenter/e3dchem/knime/testing/core/ng/WorkflowTest.java#L120-L137

There are 2 possible solutions:

* Modify the loop such that if any pool returns `-1` then `-1` is used as the final value, thereby preventing the failed check in the `MemoryUsage` constructor call
* As the only value used in `WorkflowMemLeakTest` is the value returned from `MemoryUsage#getUsed()`, update the `getHeapUsage()` method to return a `long` with only the sum of those values.  However `MemoryUsage#getMax()` is used for logging in `WorkflowExecuteTest`

The former approach has the advantage of retaining binary compatibility, both approaches require some modification to the reporting here:

https://github.com/3D-e-Chem/knime-testflow/blob/1fa09ace6c82f3d84d21c6e3fe5cb479ceb770a2/plugin/src/java/nl/esciencecenter/e3dchem/knime/testing/core/ng/WorkflowExecuteTest.java#L123-L130

**Comment by sverhoeven** [comment]
Fix of #15 has been published in v1.0.5 release on https://3d-e-chem.github.io/updates/5.1/ update site.
