### ISSUE TITLE
knime process stuck during verify on macosx 

### ISSUE THREAD

**Issue by sverhoeven** [3D-e-Chem/knime-testflow#3]
Running a test workflow on MacOS X will cause Knime to start up and use 100% cpu, but not do anything else.

**Comment by sverhoeven** [comment]
Adding `-XstartOnFirstThread` to tycho-surefire-plugin argline did not help. 
See http://wiki.eclipse.org/Tycho/FAQ#How_do_I_add_OS-specific_flags.3F

**Comment by AJK-dev** [comment]
I tried this suggestion (https://www.eclipse.org/swt/faq.php#swtawtosxmore), but unfortunately then the testflow cannot correctly initialize eclipse (org.eclipse.core.runtime.AssertionFailedException). 

Other suggestions that didn't work were:
- Suppress the KNIME splash screen during startup (<appArgLine>-nosplash</appArgLine>)
- Use Apple specific modifiers (e.g. -Dapple.awt.graphics.UseQuartz=true, -Dapple.laf.useScreenMenuBar=true) 
- use Apple specific libraries in the testflow file, e.g. com.apple.concurrent.Dispatch + getNonBlockingMainQueueExecutor
- Modifier -Djava.awt.headless=true -> but then fails to generate the views (maybe suppress the views in the flow configuration to execute the testflow correctly?)
- Modifier for the toolkit  -Dawt.toolkit=sun.awt.HToolkit
- and some other stuff that I didn't record.

**Comment by AJK-dev** [comment]
PS: This is probably also related to [this Eclipse bug report](https://bugs.eclipse.org/bugs/show_bug.cgi?id=502538): also see [the forum discussion here](https://www.eclipse.org/forums/index.php/t/1081614/)

**Comment by AJK-dev** [comment]
This workaround fixes the problem, but make sure to set useUIThread to false for mac os x in the test pom.xml.
